name: Validate Responsive Framework

on:
  workflow_call:
    secrets:
      EOA_ACCOUNT_PASSWORD:
        required: true
    inputs:
      EOA_API_KEY:
        required: true
        type: string
      mode:
        required: false
        type: string
        default: 'artifact'

jobs:
  validate:
    name: Capture and compare screenshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: npm install
        working-directory: ./emailonacid
      - name: Capture screenshots
        run: npm run eoa
        working-directory: ./emailonacid
        env:
          EOA_ACCOUNT_PASSWORD: ${{ secrets.EOA_ACCOUNT_PASSWORD }}
          EOA_API_KEY: ${{ inputs.EOA_API_KEY }}
      - name: Publish screenshots for GitHub Pages
        if: ${{ inputs.mode == 'website' }}
        uses: actions/upload-pages-artifact@v4
        with: 
          path: output
      - name: Copy screenshots for caching
        if: ${{ inputs.mode == 'cache' }}
        run: mkdir -p diff/compare && cp -r output/*.png diff/compare
      - name: List files in the repository
        run: find ${{ github.workspace }} -ls
      - name: Cache screenshots
        if: ${{ inputs.mode == 'cache' }}
        uses: actions/cache/save@v4
        with:
          path: diff/compare
          key: ${{ github.run_id }}-screenshots
      - name: List files in the repository after caching
        run: find ${{ github.workspace }} -ls
