name: Validate Responsive Framework

permissions:
  pull-requests: write

on:
  workflow_call:

jobs:
  validate:
    name: Capture and compare screenshots
    runs-on: ubuntu-latest
    environment:
      name: eoa
      url: ${{ (steps.eoa-report.conclusion == 'success' || steps.diff-report.conclusion == 'success') && steps.variables.outputs.EOA_URL || '' }}
    steps:
      - id: variables
        run: echo "EOA_URL=https://www.artifact.ci/artifact/view/${{ github.repository }}/run/${{ github.run_id }}.${{ github.run_attempt }}/eoa" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v5
        with:
          lfs: true
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Restore diff from cache
        id: cache-diff-restore
        uses: actions/cache/restore@v4
        with:
          path: diff
          key: ${{ hashFiles('emailonacid/clients.txt') }}-${{ hashFiles('source/latest.html') }}-${{ hashFiles('output/*.png') }}-diff
      - name: Copy baseline screenshots for caching
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        run: mkdir -p diff/base && cp -r output/*.png diff/base
      - name: Install dependencies
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: ./emailonacid
      - name: Capture screenshots
        id: screenshots
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        run: npm run eoa
        working-directory: ./emailonacid
        env:
          EOA_ACCOUNT_PASSWORD: ${{ secrets.EOA_ACCOUNT_PASSWORD }}
          EOA_API_KEY: ${{ vars.EOA_API_KEY }}
      - name: Copy compare screenshots for caching
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        run: mkdir -p diff/compare && cp -r output/*.png diff/compare
      - name: Compare screenshots
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        id: create-screenshots
        run: mkdir -p ../diff/diff && npm run diff
        working-directory: ./emailonacid
      - name: Generate report screenshots
        if: steps.cache-diff-restore.outputs.cache-hit != 'true' && (success() || steps.create-screenshots.conclusion == 'failure')
        run: npm run report-ci
        working-directory: ./emailonacid
      - name: Save diff to cache
        if: steps.cache-diff-restore.outputs.cache-hit != 'true'
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: diff
          key: ${{ steps.cache-diff-restore.outputs.cache-primary-key }}
      - name: Fail if there are visual differences
        id: check-diff
        run: |
          cat diff/result.json
          exit $(jq -r .totalFailed diff/result.json)
      - name: Generate report screenshots
        # Generate gallery if no differences were found
        run: npm run gallery
        working-directory: ./emailonacid
      - name: Publish screenshot page as artifact
        id: screenshot-report
        uses: actions/upload-artifact@v4
        with:
          name: eoa
          path: output
      - name: Publish diff report as artifact
        id: diff-report
        if: failure() && steps.check-diff.conclusion == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: eoa
          path: diff
      - name: Add PR comment
        if: failure() && steps.check-diff.conclusion == 'failure'
        uses: actions/github-script@v8
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### :warning: Your changes introduced visual differences.
              1. First [login here](${{ steps.variables.outputs.EOA_URL }})
              2. Then [view the differences here](${{ steps.variables.outputs.EOA_URL }}/index.html)`
            })
